### ISSUE TITLE
Некорректное направление

### ISSUE THREAD

**Issue by Irbis01** [GyverLibs/GyverEncoder#2]
При использовании некорректно определяется направление. Метод setDirection ни на что не влияет. Код:
`#define CLK 10
#define DT 9
#define SW 8

#include "GyverEncoder.h"
Encoder enc1(CLK, DT, SW, TYPE2);  // для работы c кнопкой

void setup() {
  Serial.begin(9600);
}

void loop() {
  // обязательная функция отработки. Должна постоянно опрашиваться
  enc1.tick();
  
  if (enc1.isTurn()) {     // если был совершён поворот (индикатор поворота в любую сторону)
    // ваш код
  }
  
  if (enc1.isRight()) Serial.println("Right");         // если был поворот
  if (enc1.isLeft()) Serial.println("Left");
  
  if (enc1.isRightH()) Serial.println("Right holded"); // если было удержание + поворот
  if (enc1.isLeftH()) Serial.println("Left holded");
  
  //if (enc1.isPress()) Serial.println("Press");         // нажатие на кнопку (+ дебаунс)
  //if (enc1.isRelease()) Serial.println("Release");     // то же самое, что isClick
  
  if (enc1.isClick()) Serial.println("Click");         // одиночный клик
  if (enc1.isSingle()) Serial.println("Single");       // одиночный клик (с таймаутом для двойного)
  if (enc1.isDouble()) Serial.println("Double");       // двойной клик
  
  
  if (enc1.isHolded()) Serial.println("Holded");       // если была удержана и энк не поворачивался
  //if (enc1.isHold()) Serial.println("Hold");         // возвращает состояние кнопки
}`

**Comment by Irbis01** [comment]
НО, если изменить вручную CLK и DT при инициализации объекта enc1, то все работает как надо
#define CLK 10
#define DT 9
#define SW 8
Encoder enc1(DT, CLK, SW, TYPE2);

**Comment by Irbis01** [comment]
В сериалпорте надписи Left появляются при вращении ручки энкодера вправо вне зависимости от того, что передается в setDirection
![norm](https://user-images.githubusercontent.com/60773549/154644818-49980da8-c1b2-4933-b130-acc4a98a7fb5.JPG)
![reverse](https://user-images.githubusercontent.com/60773549/154644826-a0f6558a-e06a-40da-be30-a176bba6f49f.JPG)

**Comment by GyverLibs** [comment]
В указанном примере setDirection() нигде не вызывается. Но по коду библиотеки - да, это косяк, поправлю. Метод будет работать только для отличных от avr архитектур

**Comment by GyverLibs** [comment]
Также библиотека сильно устарела, рекомендуется использовать EncButton
https://github.com/GyverLibs/EncButton

**Comment by GyverLibs** [comment]
пофиксил

**Comment by Irbis01** [comment]
> 

в конкретном коде - да, не вызывается. Я это делал на отдельных тестах и метод ни на что не влиял. Благодарю

**Comment by Irbis01** [comment]
> Также библиотека сильно устарела, рекомендуется использовать EncButton https://github.com/GyverLibs/EncButton

с новой версией у меня перестает работать сервопривод. Пины проверял - висят на разных

**Comment by GyverLibs** [comment]
> с новой версией у меня перестает работать сервопривод

этого не может быть =) Вот тестовый скетч, всё отлично работает

```cpp
#include <EncButton.h>
EncButton<EB_TICK, 2, 3, 4> enc;

#include <Servo.h>
Servo servo;

void setup() {
  Serial.begin(9600);
  servo.attach(5);
}

void loop() {
  enc.tick();
  if (enc.turn()) servo.write(enc.counter);
}
```

**Comment by Irbis01** [comment]
![image](https://user-images.githubusercontent.com/60773549/154671978-59525d86-5c9f-4857-bf18-5c3cfb042e8a.png)
скачал по ссылке, что вы выше присылали библиотеку. Я раньше использовали EncButton2 и серво с ней не работала. Сейчас использую код, что вы прислали. Она тоже не хочет работать

**Comment by Irbis01** [comment]
Проверил. Пришлось дописать отключение/выключение серво. Все работает. С EncButton2 не работало. Чуть позже проверю старый код. Если получится повторить, то куда мне можно будет прислать видео и код?

**Comment by Irbis01** [comment]
`
#include <EncButton.h>
EncButton<EB_TICK, 10, 9, 8> enc;
#include <Servo.h>
Servo servo;
#define SERVO_POWER 4
#define servoON() digitalWrite(SERVO_POWER, 1)
#define servoOFF() digitalWrite(SERVO_POWER, 0)
void setup() {
  Serial.begin(9600);
  servo.attach(5);
  servoON();
}
void loop() {
  enc.tick();
  if (enc.turn()) 
  {
    Serial.println(enc.counter);
    servo.write(enc.counter);
  }
}`

**Comment by Irbis01** [comment]
```c++
#include <EncButton.h>
EncButton<EB_TICK, 10, 9, 8> enc;

#include <Servo.h>
Servo servo;
#define SERVO_POWER 4
#define servoON() digitalWrite(SERVO_POWER, 1)
#define servoOFF() digitalWrite(SERVO_POWER, 0)

void setup() {
  Serial.begin(9600);
  servo.attach(5);
  servoON();
}

void loop() {
  enc.tick();
  if (enc.turn()) 
  {
    Serial.println(enc.counter);
    servo.write(enc.counter);
  }
}
```

**Comment by Irbis01** [comment]
с таким кодом отказывается работать. Делал на основе кода из examples

```c++
#define SERVO_POWER 4
#define SERVO_PIN 5
#include <Servo.h>
Servo servo;
#define servoON() digitalWrite(SERVO_POWER, 1)
#define servoOFF() digitalWrite(SERVO_POWER, 0)


#define EB_FAST 30     // таймаут быстрого поворота, мс
#define EB_DEB 50      // дебаунс кнопки, мс
#define EB_HOLD 1000   // таймаут удержания кнопки, мс
#define EB_STEP 500    // период срабатывания степ, мс
#define EB_CLICK 400   // таймаут накликивания, мс
#include <EncButton2.h>
#define ENC_SW 8
#define ENC_DT 9
#define ENC_CLK 10
EncButton2<EB_ENCBTN> encoder(INPUT, ENC_CLK, ENC_DT, ENC_SW);

void setup() {
  Serial.begin(9600);
  servo.attach(5);
  servoON();
}

void loop() {
  encoder.tick();
  if (encoder.turn()) 
  {
    Serial.println(encoder.counter);
    servo.write(encoder.counter);
  }
}
```

**Comment by Irbis01** [comment]
О_О
 а так работает!
 Я просто переместил инициализацию энкодера вверх, перед инициализацией серво, как в вашем примере. По логике проблемы в этом быть не должно
 ```c++
 #define EB_FAST 30     // таймаут быстрого поворота, мс
#define EB_DEB 50      // дебаунс кнопки, мс
#define EB_HOLD 1000   // таймаут удержания кнопки, мс
#define EB_STEP 500    // период срабатывания степ, мс
#define EB_CLICK 400   // таймаут накликивания, мс
#include <EncButton2.h>
#define ENC_SW 8
#define ENC_DT 9
#define ENC_CLK 10
EncButton2<EB_ENCBTN> encoder(INPUT, ENC_CLK, ENC_DT, ENC_SW);

#define SERVO_POWER 4
#define SERVO_PIN 5
#include <Servo.h>
Servo servo;
#define servoON() digitalWrite(SERVO_POWER, 1)
#define servoOFF() digitalWrite(SERVO_POWER, 0)




void setup() {
  Serial.begin(9600);
  servo.attach(5);
  servoON();
}

void loop() {
  encoder.tick();
  if (encoder.turn()) 
  {
    Serial.println(encoder.counter);
    servo.write(encoder.counter);
  }
}
 ```

**Comment by GyverLibs** [comment]
чёрт возьми! Всё таки был баг, из за которого encbutton2 лезла не в свою область памяти и портила переменные. Я всё пофиксил, спасибо за репорт!

**Comment by Irbis01** [comment]
Рад помочь ;) И вам большое спасибо за помощь, это очень помогло
