### ISSUE TITLE
Опрос энкодера с прерываниями

### ISSUE THREAD

**Issue by brightproject** [GyverLibs/GyverEncoder#3]
Подключал такой энкодер.
https://alexgyver.ru/wp-content/uploads/2021/06/enc_scheme.jpg
Специально пины к земле или к питанию не подтягивал.
В нагруженном коде, даже на прерываниях - энкодер вытворял такую дичь.
Пока не прописал
`enc1.setPinMode(LOW_PULL);`
Энкодер не стал адекватно реагировать на повороты.
Также раньше прописывал принудительно
`enc1.setType(TYPE2);`
А с подтяжкой закомментировал эту строку и все работает без двойного поворота.

**Comment by GyverLibs** [comment]
Пины нужно обязательно подтянуть, внешне или внутреннее
